### ISSUE TITLE
Do you have a specific license for your code?

### ISSUE THREAD

**Issue by EmillerOpenwhere** [trueprice/python-graph-clustering#1]
Just curious. I'd like to use it.

**Comment by trueprice** [comment]
I added an MIT license to the repo. Generally, feel free to use/modify/distribute the code in any way you see fit, but consider adding a link to the repo in your code. Thanks!

**Comment by EmillerOpenwhere** [comment]
THANKS!

**Comment by EmillerOpenwhere** [comment]
Thanks Fam
